<?xml version="1.0" encoding="UTF-8"?>
<pmd xmlns="http://pmd.sourceforge.net/report/2.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://pmd.sourceforge.net/report/2.0.0 http://pmd.sourceforge.net/report_2_0_0.xsd" version="6.44.0" timestamp="2023-10-12T22:11:17.007">
<file name="/mnt/c/Users/Valentino/Documents/Universita/Tesi/Tesi/Pacchetto_di_replicabilita/Correttiva/src/CWE-640/bad$cd31cc397fe17389d95b83d6a9caa46eebc54faf$2$UaaResetPasswordService.java">
<violation beginline="62" endline="62" begincolumn="13" endcolumn="51" rule="PreserveStackTrace" ruleset="Best Practices" package="org.cloudfoundry.identity.uaa.login" class="UaaResetPasswordService" method="resetPassword" externalInfoUrl="https://pmd.github.io/pmd-6.44.0/pmd_rules_java_bestpractices.html#preservestacktrace" priority="3">
New exception is thrown in catch block, original stack trace may be lost
</violation>
<violation beginline="107" endline="107" begincolumn="27" endcolumn="79" rule="UnnecessaryFullyQualifiedName" ruleset="Code Style" package="org.cloudfoundry.identity.uaa.login" class="UaaResetPasswordService" method="forgotPassword" externalInfoUrl="https://pmd.github.io/pmd-6.44.0/pmd_rules_java_codestyle.html#unnecessaryfullyqualifiedname" priority="4">
Unnecessary use of fully qualified name 'org.cloudfoundry.identity.uaa.login.NotFoundException' due to existing same package import 'org.cloudfoundry.identity.uaa.login.*'
</violation>
<violation beginline="128" endline="128" begincolumn="17" endcolumn="42" rule="UselessParentheses" ruleset="Code Style" package="org.cloudfoundry.identity.uaa.login" class="UaaResetPasswordService" method="isUserModified" externalInfoUrl="https://pmd.github.io/pmd-6.44.0/pmd_rules_java_codestyle.html#uselessparentheses" priority="4">
Useless parentheses.
</violation>
</file>
</pmd>
