<?xml version="1.0" encoding="UTF-8"?>
<pmd xmlns="http://pmd.sourceforge.net/report/2.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://pmd.sourceforge.net/report/2.0.0 http://pmd.sourceforge.net/report_2_0_0.xsd" version="6.44.0" timestamp="2023-10-12T21:17:21.511">
<file name="/mnt/c/Users/Valentino/Documents/Universita/Tesi/Tesi/Pacchetto_di_replicabilita/Correttiva/src/CWE-502/bad$4092ede58da51af9a21e4825fbad0d9a3ef5a223$33$XMSSPrivateKeyParameters.java">
<violation beginline="98" endline="101" begincolumn="13" endcolumn="13" rule="IdenticalCatchBranches" ruleset="Code Style" package="org.bouncycastle.pqc.crypto.xmss" class="XMSSPrivateKeyParameters" method="XMSSPrivateKeyParameters" externalInfoUrl="https://pmd.github.io/pmd-6.44.0/pmd_rules_java_codestyle.html#identicalcatchbranches" priority="3">
'catch' branch identical to 'IOException' branch
</violation>
<violation beginline="288" endline="288" begincolumn="13" endcolumn="89" rule="PreserveStackTrace" ruleset="Best Practices" package="org.bouncycastle.pqc.crypto.xmss" class="XMSSPrivateKeyParameters" method="toByteArray" externalInfoUrl="https://pmd.github.io/pmd-6.44.0/pmd_rules_java_bestpractices.html#preservestacktrace" priority="3">
New exception is thrown in catch block, original stack trace may be lost
</violation>
</file>
</pmd>
