<?xml version="1.0" encoding="UTF-8"?>
<pmd xmlns="http://pmd.sourceforge.net/report/2.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://pmd.sourceforge.net/report/2.0.0 http://pmd.sourceforge.net/report_2_0_0.xsd" version="6.44.0" timestamp="2023-10-12T17:46:00.346">
<file name="/mnt/c/Users/Valentino/Documents/Universita/Tesi/Tesi/Pacchetto_di_replicabilita/Correttiva/src/CWE-22/bad$f8a612df7b06729bfd6c826e1a110d4bb40dc1f5$159$RunSQLHelper.java">
<violation beginline="30" endline="30" begincolumn="26" endcolumn="73" rule="ProperLogger" ruleset="Error Prone" package="org.apache.geronimo.console.internaldb" class="RunSQLHelper" variable="VariableDeclaratorId" externalInfoUrl="https://pmd.github.io/pmd-6.44.0/pmd_rules_java_errorprone.html#properlogger" priority="3">
Logger should be defined private static final and have the correct class
</violation>
<violation beginline="55" endline="61" begincolumn="11" endcolumn="9" rule="AvoidCatchingThrowable" ruleset="Error Prone" package="org.apache.geronimo.console.internaldb" class="RunSQLHelper" method="createDB" externalInfoUrl="https://pmd.github.io/pmd-6.44.0/pmd_rules_java_errorprone.html#avoidcatchingthrowable" priority="3">
A catch statement should never catch throwable since it includes errors.
</violation>
<violation beginline="56" endline="56" begincolumn="17" endcolumn="17" rule="AvoidInstanceofChecksInCatchClause" ruleset="Error Prone" package="org.apache.geronimo.console.internaldb" class="RunSQLHelper" method="createDB" externalInfoUrl="https://pmd.github.io/pmd-6.44.0/pmd_rules_java_errorprone.html#avoidinstanceofchecksincatchclause" priority="3">
An instanceof check is being performed on the caught exception.  Create a separate catch clause for this exception type.
</violation>
<violation beginline="138" endline="138" begincolumn="14" endcolumn="24" rule="UselessParentheses" ruleset="Code Style" package="org.apache.geronimo.console.internaldb" class="RunSQLHelper" method="runSQL" externalInfoUrl="https://pmd.github.io/pmd-6.44.0/pmd_rules_java_codestyle.html#uselessparentheses" priority="4">
Useless parentheses.
</violation>
<violation beginline="138" endline="138" begincolumn="31" endcolumn="54" rule="UselessParentheses" ruleset="Code Style" package="org.apache.geronimo.console.internaldb" class="RunSQLHelper" method="runSQL" externalInfoUrl="https://pmd.github.io/pmd-6.44.0/pmd_rules_java_codestyle.html#uselessparentheses" priority="4">
Useless parentheses.
</violation>
<violation beginline="167" endline="168" begincolumn="15" endcolumn="13" rule="EmptyCatchBlock" ruleset="Error Prone" package="org.apache.geronimo.console.internaldb" class="RunSQLHelper" method="runSQL" externalInfoUrl="https://pmd.github.io/pmd-6.44.0/pmd_rules_java_errorprone.html#emptycatchblock" priority="3">
Avoid empty catch blocks
</violation>
<violation beginline="170" endline="172" begincolumn="11" endcolumn="9" rule="AvoidCatchingThrowable" ruleset="Error Prone" package="org.apache.geronimo.console.internaldb" class="RunSQLHelper" method="runSQL" externalInfoUrl="https://pmd.github.io/pmd-6.44.0/pmd_rules_java_errorprone.html#avoidcatchingthrowable" priority="3">
A catch statement should never catch throwable since it includes errors.
</violation>
</file>
</pmd>
